project:
  type: website
  output-dir: docs
  
website:
  title: "Andrew Mosbo"
  page-footer: "Copyright 2023, YOUR NAME" 
  reader-mode: false
  navbar:
    pinned: true
    left:
      - text: Project
        href: danlfinal.qmd
      - text: Homework
        menu:
          - text: hw0
            href: hw0.qmd
          - text: HW1
            href: hw1.qmd
          - text: HW3
            href: hw3qmd.qmd
            
format:
  html:
    theme:
      light: flatly
      dark: [darkly, theme-dark.scss]
    # mainfont: Georgia, serif;
    # mainfont: Gill Sans, sans-serif;
    toc: true
    include-after-body: target_blank.html
