---
title: "lab2"
editor: visual
---



```{r}
library(tidyverse)
library(dplyr)
library(socviz)
library(lubridate)
library(geofacet)
library(ggthemes)
```


```{r}
unemp_house_prices <- read_csv(
  'https://bcdanl.github.io/data/unemp_house_prices.csv')

adjust_labels <- as_labeller(
  function(x) {
    case_when(
      x == "New Hampshire" ~ "N. Hampshire",
      x == "District of Columbia" ~ "DC",
      TRUE ~ x
    )
  }
)


dat08 <- filter(unemp_house_prices, ymd(date) > ymd('2008/01/01'))

ggplot(data = filter(unemp_house_prices, ymd(date) > ymd('2008/01/01')), aes(x = ymd(date), y = unemploy_perc)) +
  geom_area(fill = 'blue3') +
  geom_line() + 
  scale_x_date(breaks = ymd("2009/01/01","2011/01/01","2013/01/01","2015/01/01","2017/01/01"),
               labels = c("'09","'11","'13","'15","'17")) +
  facet_geo(~state, labeller = adjust_labels)
  

```

```{r}
election_panel <- read_csv(
  'https://bcdanl.github.io/data/election_panel.csv')


mp <- county_map



dat <- left_join(mp, election_panel)

ggplot(filter(dat, !is.na(year))) + 
  geom_polygon(aes(x = long, y = lat, group = group, fill = pct_DEMOCRAT), color = "grey60") +
  coord_fixed() +
  theme_map() +
  facet_wrap(~year)

```




